Program 1:


package exception_handling;
import java.util.Scanner;
public class Exception_Handling {

    
    public static void main(String[] args) {
        
        Scanner sc=new Scanner(System.in);
        System.out.println("Enter two numbers to perform division:");
	int a=sc.nextInt();
	int b=sc.nextInt();
	try
	{
		int result=b/a;
		System.out.println("Result= " +result);
	}
	catch(ArithmeticException e)
	{
		System.out.println(e);
	}
}
}
    }
    
}

---------------------------------------------------------------------------------------------------

Program 2:


import java.util.Scanner;
public class Exception_Handling2 {

    
    public static void main(String[] args) {
        
        Scanner sc=new Scanner(System.in);
        System.out.println("Enter two numbers to perform division:");
	int a=sc.nextInt();
	int b=sc.nextInt();
	int[] arr=new int[10];
	try
	{
		int result=b/a;
		arr[15]=result;
		System.out.println("Result of b/a is: " +result);
	}
	catch(ArithmeticException e)
	{
		System.out.println(e);
	}
	catch(ArrayIndexOutOfBoundsException e)
	{
		System.out.println(e);
	}
	catch(Exception e)
	{
		System.out.println(e);
	}
	
    }
    
}

---------------------------------------------------------------------------------------------------------

Program 3:


import java.util.Arrays;
import java.util.*;
public class Exception_Handling3 {

    
    public static void main(String[] args) {
        
        Scanner sc=new Scanner(System.in);
	int[] arr={10,20,13,24,0,45};
	System.out.println("Array: " + Arrays.toString(arr));
     	System.out.println("Enter the address of two numbers from array to perform division:");
	int a=sc.nextInt();
	int b=sc.nextInt();
	try
	{
		int result=arr[a]/arr[b];
		System.out.println("Result: " +result);
	}
	catch(ArrayIndexOutOfBoundsException e)
	{
		throw new IndexOutOfBoundsException();
	}
	catch(ArithmeticException e)
	{
		throw e;
	}
	catch(Exception e)
	{
		throw e;
	}
	
    }
    
}

----------------------------------------------------------------------------------------------------------

Program 4:

import java.util.Arrays;
import java.util.*;
public class Exception_Handling3 {

    
    public static void main(String[] args) {
        
        Scanner sc=new Scanner(System.in);
	int[] arr={10,20,13,24,0,45};
	System.out.println("Array: " + Arrays.toString(arr));
     	System.out.println("Enter the address of two numbers from array to perform division:");
	int a=sc.nextInt();
	int b=sc.nextInt();
	try
	{
		int result=arr[a]/arr[b];
		System.out.println("Result: " +result);
	}
	catch(ArrayIndexOutOfBoundsException e)
	{
		throw new IndexOutOfBoundsException();
	}
	catch(ArithmeticException e)
	{
		throw e;
	}
	catch(Exception e)
	{
		throw e;
	}
	
    }
    
}

--------------------------------------------------------------------------------------------------------------------

Program 5:


import java.util.*;
public class Exception_Handling5 {

    
    public static void main(String[] args) {
        
        Scanner sc=new Scanner(System.in);
	try
	{
     		System.out.println("Enter two numbers to perform division:");
		int a=sc.nextInt();
		int b=sc.nextInt();
		System.out.println(" " +a/b);
	}
	catch(InputMismatchException e)
	{
		System.out.println(e);
	}
	catch(ArithmeticException e)
	{
		System.out.println(e);
	}
	catch(Exception e)
	{
		System.out.println(e);
	}
	
    }
    
}
